;<?Ini Version="SunnyUI V3.8.0.1" Encoding="iso-8859-1"?>
;<?Update Time="2026-07-02 14:09:24"?>

[Setup]
ServerIP=192.168.1.2
ServerTcpPort=9090
SerialPort=COM1
FilePath=E:\gitcode\RfidDemo\bin\Debug\SnLog
LogPath=E:\gitcode\RfidDemo\bin\Debug\logs
XmlPath=E:\gitcode\RfidDemo\bin\Debug\Xml
BaudRate=115200
Language=1


